name: Run Tests

on:
    pull_request:
        branches:
            - master
    workflow_dispatch:

jobs:
    run-tests:
        name: run unit tests
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   name: Setup Go
                uses: actions/setup-go@v4
                with:
                    go-version: '1.21.x'
            -   name: Run Tests
                run: bash ./run-tests.sh